const assert=require('node:assert/strict'),fs=require('node:fs');
const core=require('../mcat-v2-engine.js'),course=require('../mcat-course-engine.js'),data=JSON.parse(fs.readFileSync('data/mcat-course.json')),coaching=JSON.parse(fs.readFileSync('data/mcat-v2.json'));
const now=new Date(2026,8,6,12).getTime();let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name);};
test('Curriculum has 45 unique lessons, 15 complete chapters, 270 unique questions, and 12 stable placement items',()=>{assert.equal(data.units.length,45);assert.equal(data.chapters.length,15);assert.equal(data.units.filter(u=>u.placementEligible).length,12);const ids=data.units.flatMap(u=>u.questions.map(q=>q.id));assert.equal(ids.length,270);assert.equal(new Set(ids).size,270);assert.equal(new Set(data.chapters.flatMap(c=>c.units)).size,45);for(const u of data.units){assert.equal(u.questions.filter(q=>q.kind==='delayed').length,3);assert.equal(u.questions.filter(q=>q.kind==='check').length,2);assert.ok(data.chapters.some(c=>c.id===u.chapter&&c.units.includes(u.id)));for(const q of u.questions){assert.equal(new Set(q.options).size,q.options.length,q.id);assert.ok(q.options[q.answer]);}for(const id of u.prerequisites)assert.ok(data.units.some(v=>v.id===id));}});
test('No prerequisite cycles',()=>{function visit(id,path=[]){assert.ok(!path.includes(id),path+' -> '+id);for(const next of data.units.find(u=>u.id===id).prerequisites)visit(next,[...path,id]);}data.units.forEach(u=>visit(u.id));});
test('Three delayed applications stay spaced and cannot be answered out of order',()=>{const s=course.normalize({}),u=data.units[0],r=course.record(s,u.id),qs=u.questions.filter(q=>q.kind==='delayed');r.completedAt=now;course.refreshSchedule(s,u);assert.equal(r.dueAt,now+core.DAY);assert.equal(course.answer(s,u,qs[1],qs[1].answer,'sure',now+core.DAY),null);assert.equal(course.answer(s,u,qs[0],qs[0].answer,'sure',now),null);course.answer(s,u,qs[0],qs[0].answer,'sure',now+core.DAY);assert.equal(r.dueAt,now+core.DAY*4);course.answer(s,u,qs[1],(qs[1].answer+1)%4,'sure',now+core.DAY*4);assert.equal(r.dueAt,now+core.DAY*5);course.answer(s,u,qs[2],qs[2].answer,'sure',now+core.DAY*5);assert.equal(r.dueAt,null);assert.equal(r.attempts.length,3);course.answer(s,u,qs[1],qs[1].answer,'sure',now+core.DAY*20);assert.equal(r.attempts[1].correct,false);assert.equal(r.attempts.length,3);});
test('v1 records migrate without changing their original answers',()=>{const s=course.normalize({}),u=data.units[0],r=course.record(s,u.id),q=u.questions.find(q=>q.kind==='delayed');r.completedAt=now-core.DAY*5;r.delayedAt=now-core.DAY*4;r.dueAt=null;r.attempts=[{qId:q.id,kind:'delayed',correct:true,chosen:q.answer,ts:r.delayedAt}];const old=JSON.stringify(r.attempts);course.refreshSchedule(s,u);assert.equal(r.dueAt,now-core.DAY);assert.equal(JSON.stringify(r.attempts),old);assert.notEqual(course.nextDelayed(s,u).id,q.id);});
test('Assistance and prior exposure remain separate from first independent answers',()=>{assert.deepEqual(core.evidence([{correct:true},{correct:true,assisted:true},{correct:false,repeat:true,assisted:true}]),{independent:{correct:1,total:1},assisted:{correct:1,total:1},repeat:{correct:0,total:1}});assert.equal(core.nextSupport([],'cars'),'guided');assert.equal(core.nextSupport([{kind:'cars',completedAt:1},{kind:'cars',completedAt:2}],'cars'),'light');});
test('All 48 quantitative variants have finite solutions and distinct setup choices',()=>{const ids=[];for(const skill of Object.keys(core.SKILLS))for(let i=0;i<8;i++){const q=core.quant(skill,i);ids.push(q.id);assert.equal(new Set(q.setups).size,3,q.id);assert.ok(Number.isFinite(q.value));assert.ok(core.numeric(String(q.value),q.value).correct);assert.equal(core.numeric(String(q.value*2),q.value).correct,false);assert.ok(q.errors[q.answer].length>20);if(q.graph){const [a,b]=q.graph.points;assert.equal((b[1]-a[1])/(b[0]-a[0]),q.value);}}assert.equal(new Set(ids).size,48);});
test('Numerical parser rejects blank, expressions, units, infinities and accepts scientific notation',()=>{for(const x of ['',' ','Infinity','1/2','4 mg','0x10','NaN'])assert.equal(core.numeric(x,0),null,x);assert.ok(core.numeric('4e-2',.04).correct);assert.ok(core.numeric('2.70',2.69897).correct);});
test('Diagnostic claims stay provisional and handle mixed or no observed misses',()=>{assert.equal(core.diagnose([{domain:'content',correct:false},{domain:'graph',correct:true}]).cause,'content');assert.equal(core.diagnose([{domain:'content',correct:false},{domain:'math',correct:false}]).cause,'uncertain');assert.equal(core.diagnose([{domain:'content',correct:true}]).cause,'uncertain');});
function input(s){return {start:'2026-09-06',now,units:data.units,records:{},coaches:coaching.coaches};}
test('Weekly budget respects rest days, observed durations, and target dates',()=>{const s=core.normalize({});s.weekly.availability=[30,30,0,30,30,60,0];s.weekly.targetDate='2026-09-10';s.durations=[{type:'course',ms:22*60000},{type:'course',ms:18*60000}];assert.equal(core.duration(s,'course',15),20);const days=core.week(s,input(s));assert.equal(days.length,7);for(const d of days){assert.ok(d.tasks.reduce((n,t)=>n+t.minutes,0)<=d.budget);if(!d.budget||d.date>s.weekly.targetDate)assert.equal(d.tasks.length,0);}});
test('Exam time is explicit and its review moves to the next day that can fit it',()=>{const s=core.normalize({});s.weekly.availability=[0,30,30,30,30,30,30];s.weekly.exams=[{id:'e',name:'Official practice',date:'2026-09-06',minutes:120}];const days=core.week(s,input(s));assert.equal(days[0].tasks[0].minutes,120);assert.equal(days[1].tasks.length,0);assert.ok(days[2].tasks.some(t=>t.type==='externalReview'));assert.equal(days.flatMap(d=>d.tasks).filter(t=>t.type==='externalReview').length,1);});
test('Completed tasks persist and saved work is not duplicated in the rolling week',()=>{const s=core.normalize({});s.weekly.availability=[30,30,30,30,30,30,30];s.weekly.active={id:'course:protein-structure',type:'course',key:'protein-structure',title:'Saved',minutes:15,day:'2026-09-05'};s.weekly.done.old={id:'math:units',type:'math',key:'units',title:'Units',minutes:5,day:'2026-09-06'};const days=core.week(s,input(s));assert.ok(days[0].tasks.some(t=>t.done&&t.id==='math:units'));assert.equal(days.flatMap(d=>d.tasks).filter(t=>t.id==='course:protein-structure').length,1);});
test('Latest entered official results and observed misses create transparent weekly priorities',()=>{const s=core.normalize({});s.weekly.availability=[30,30,30,30,30,30,30];s.weekly.exams=[{id:'official',name:'Practice',source:'official',date:'2026-09-05',reviewedAt:now-core.DAY,minutes:120,scores:{chemPhys:124,cars:129,bioBiochem:128,psychSoc:127}}];let days=core.week(s,input(s));assert.equal(days[0].tasks[0].key,'buffer-balance');assert.ok(days[0].tasks[0].reason.includes('entered official'));const i=input(s);i.records={'protein-structure':{completedAt:now-core.DAY,attempts:[{kind:'check',correct:false,ts:now-core.DAY}],reviewedAt:0}};days=core.week(s,i);assert.ok(days[0].tasks.some(t=>t.kind==='review'&&t.key==='protein-structure'));});
test('Every coach maps to a real passage and lesson, with paragraph-specific CARS models',()=>{const cars=JSON.parse(fs.readFileSync('data/mcat-cars.json')),sci=JSON.parse(fs.readFileSync('data/mcat-science-passages.json'));assert.equal(coaching.coaches.length,8);for(const c of coaching.coaches){const p=(c.kind==='cars'?cars:sci).find(p=>p.id===c.passageId);assert.ok(p);assert.ok(data.units.some(u=>u.id===c.unitId));if(c.kind==='cars')assert.equal(c.model.filter(m=>m.label.startsWith('Paragraph')).length,p.text.split(/\n\n+/).length);assert.equal(c.hints.length,2);assert.equal(c.questionHints.length,2);}});
console.log(`${checks} v2 logic and content checks passed.`);
